# Curated word lists per length, used as both the pool of secret answers and
# the dictionary of valid guesses. The host picks the length (4-6) in the lobby.
import random

WORDS_4 = [
    "ABLE", "ACID", "AGED", "ALSO", "AREA", "ARMY", "AWAY", "BABY", "BACK", "BALL",
    "BAND", "BANK", "BARE", "BARN", "BASE", "BATH", "BEAM", "BEAN", "BEAR", "BEAT",
    "BEEF", "BEEN", "BEER", "BELL", "BELT", "BEND", "BEST", "BIKE", "BIRD", "BITE",
    "BLOW", "BLUE", "BOAT", "BODY", "BOLD", "BOLT", "BOMB", "BOND", "BONE", "BOOK",
    "BOOM", "BOOT", "BORN", "BOSS", "BOTH", "BOWL", "BULK", "BURN", "BUSH", "BUSY",
    "CAFE", "CAGE", "CAKE", "CALL", "CALM", "CAMP", "CARD", "CARE", "CART", "CASE",
    "CASH", "CAST", "CAVE", "CELL", "CHAT", "CHIP", "CITY", "CLAY", "CLIP", "CLUB",
    "CLUE", "COAL", "COAT", "CODE", "COIN", "COLD", "COME", "COOK", "COOL", "COPE",
    "COPY", "CORD", "CORE", "CORN", "COST", "CREW", "CROP", "CUBE", "CURE", "CURL",
    "DARE", "DARK", "DATA", "DATE", "DAWN", "DEAD", "DEAL", "DEAR", "DEBT", "DECK",
    "DEEP", "DEER", "DENY", "DESK", "DIAL", "DICE", "DIET", "DIRT", "DISH", "DIVE",
    "DOCK", "DOLL", "DOOR", "DOSE", "DOVE", "DOWN", "DRAW", "DREW", "DROP", "DRUM",
    "DUAL", "DUCK", "DULL", "DUMP", "DUST", "DUTY", "EACH", "EARN", "EASE", "EAST",
    "EASY", "EDGE", "EDIT", "ELSE", "EVEN", "EVER", "EVIL", "EXIT", "FACE", "FACT",
    "FADE", "FAIL", "FAIR", "FALL", "FAME", "FARM", "FAST", "FATE", "FEAR", "FEED",
    "FEEL", "FEET", "FELL", "FELT", "FILE", "FILL", "FILM", "FIND", "FINE", "FIRE",
    "FIRM", "FISH", "FIST", "FIVE", "FLAG", "FLAT", "FLED", "FLEE", "FLEW", "FLIP",
    "FLOW", "FOAM", "FOLD", "FOLK", "FOND", "FOOD", "FOOL", "FOOT", "FORK", "FORM",
    "FORT", "FOUR", "FREE", "FROG", "FROM", "FUEL", "FULL", "FUND", "GAIN", "GAME",
    "GANG", "GASP", "GATE", "GAVE", "GEAR", "GIFT", "GIRL", "GIVE", "GLAD", "GLOW",
    "GLUE", "GOAL", "GOAT", "GOLD", "GOLF", "GONE", "GOOD", "GOWN", "GRAB", "GRAY",
    "GREW", "GREY", "GRID", "GRIP", "GROW", "GULF", "HAIL", "HAIR", "HALF", "HALL",
    "HALT", "HAND", "HANG", "HARD", "HARM", "HATE", "HAVE", "HAWK", "HEAD", "HEAL",
    "HEAP", "HEAR", "HEAT", "HEEL", "HELD", "HELP", "HERB", "HERD", "HERE", "HERO",
    "HIDE", "HIGH", "HILL", "HINT", "HIRE", "HOLD", "HOLE", "HOLY", "HOME", "HOOD",
    "HOOK", "HOPE", "HORN", "HOST", "HOUR", "HUGE", "HUNT", "HURT", "ICON", "IDEA",
    "INCH", "INTO", "IRON", "ITEM", "JADE", "JAIL", "JOIN", "JOKE", "JUMP", "JURY",
    "JUST", "KEEN", "KEEP", "KICK", "KILL", "KIND", "KING", "KISS", "KITE", "KNEE",
    "KNEW", "KNOT", "KNOW", "LACE", "LACK", "LADY", "LAID", "LAKE", "LAMB", "LAMP",
    "LAND", "LANE", "LAST", "LATE", "LAWN", "LAZY", "LEAD", "LEAF", "LEAN", "LEAP",
    "LEFT", "LEND", "LENS", "LESS", "LICK", "LIFE", "LIFT", "LIKE", "LIME", "LINE",
    "LINK", "LION", "LIST", "LIVE", "LOAD", "LOAF", "LOAN", "LOCK", "LOFT", "LONE",
    "LONG", "LOOK", "LOOP", "LORD", "LOSE", "LOSS", "LOST", "LOUD", "LOVE", "LUCK",
    "LUMP", "LUNG", "MAIL", "MAIN", "MAKE", "MALE", "MALL", "MANY", "MARK", "MASK",
    "MASS", "MATE", "MATH", "MAZE", "MEAL", "MEAN", "MEAT", "MEET", "MELT", "MENU",
    "MERE", "MICE", "MILD", "MILE", "MILK", "MILL", "MIND", "MINE", "MINT", "MISS",
    "MIST", "MOCK", "MODE", "MOLD", "MOLE", "MOOD", "MOON", "MORE", "MOSS", "MOST",
    "MOTH", "MOVE", "MUCH", "MULE", "MUST", "MUTE", "NAIL", "NAME", "NAVY", "NEAR",
    "NEAT", "NECK", "NEED", "NEST", "NEWS", "NEXT", "NICE", "NINE", "NODE", "NONE",
    "NOON", "NORM", "NOSE", "NOTE", "NOUN", "OATH", "OBEY", "ONCE", "ONLY", "ONTO",
    "OPEN", "ORAL", "OVEN", "OVER", "PACE", "PACK", "PAGE", "PAID", "PAIN", "PAIR",
    "PALE", "PALM", "PARK", "PART", "PASS", "PAST", "PATH", "PEAK", "PEAR", "PEEL",
    "PEER", "PILE", "PILL", "PINE", "PINK", "PIPE", "PLAN", "PLAY", "PLOT", "PLUG",
    "PLUS", "POEM", "POET", "POLE", "POLL", "POND", "POOL", "POOR", "PORE", "PORT",
    "POSE", "POST", "POUR", "PRAY", "PREY", "PROP", "PULL", "PUMP", "PURE", "PUSH",
    "QUIT", "RACE", "RACK", "RAGE", "RAIL", "RAIN", "RANK", "RARE", "RATE", "READ",
    "REAL", "REAR", "REED", "REEF", "REEL", "RELY", "RENT", "REST", "RICE", "RICH",
    "RIDE", "RING", "RIPE", "RISE", "RISK", "ROAD", "ROAM", "ROAR", "ROCK", "ROLE",
    "ROLL", "ROOF", "ROOM", "ROOT", "ROPE", "ROSE", "RUBY", "RUDE", "RUIN", "RULE",
    "RUSH", "RUST", "SAFE", "SAGE", "SAID", "SAIL", "SAKE", "SALE", "SALT", "SAME",
    "SAND", "SAVE", "SCAN", "SEAL", "SEAT", "SEED", "SEEK", "SEEM", "SEEN", "SELF",
    "SELL", "SEND", "SHED", "SHIP", "SHOE", "SHOP", "SHOT", "SHOW", "SHUT", "SICK",
    "SIDE", "SIGH", "SIGN", "SILK", "SING", "SINK", "SITE", "SIZE", "SKIN", "SKIP",
    "SLAB", "SLAM", "SLAP", "SLED", "SLID", "SLIM", "SLIP", "SLOT", "SLOW", "SNAP",
    "SNOW", "SOAP", "SOFA", "SOFT", "SOIL", "SOLD", "SOLE", "SOME", "SONG", "SOON",
    "SORT", "SOUL", "SOUP", "SOUR", "SPAN", "SPIN", "SPOT", "STAR", "STAY", "STEM",
    "STEP", "STIR", "STOP", "SUCH", "SUIT", "SURE", "SWAM", "SWAP", "SWIM", "TAIL",
    "TAKE", "TALE", "TALK", "TALL", "TAME", "TANK", "TAPE", "TASK", "TEAM", "TEAR",
    "TELL", "TEND", "TENT", "TERM", "TEST", "TEXT", "THAN", "THAT", "THAW", "THEM",
    "THEN", "THEY", "THIN", "THIS", "THUS", "TIDE", "TIDY", "TILE", "TIME", "TINY",
    "TIRE", "TOAD", "TOLD", "TOLL", "TONE", "TOOL", "TORN", "TOUR", "TOWN", "TRAP",
    "TRAY", "TREE", "TRIM", "TRIP", "TROT", "TRUE", "TUBE", "TUNA", "TUNE", "TURN",
    "TWIN", "TYPE", "UGLY", "UNIT", "UPON", "URGE", "USED", "USER", "VARY", "VAST",
    "VEIL", "VEIN", "VERY", "VICE", "VIEW", "VINE", "VISA", "VOID", "VOTE", "WADE",
    "WAGE", "WAIT", "WAKE", "WALK", "WALL", "WAND", "WANT", "WARD", "WARM", "WARN",
    "WASH", "WAVE", "WEAK", "WEAR", "WEED", "WEEK", "WELL", "WENT", "WERE", "WEST",
    "WHAT", "WHEN", "WHIP", "WIDE", "WIFE", "WILD", "WILL", "WIND", "WINE", "WING",
    "WINK", "WIPE", "WIRE", "WISE", "WISH", "WOLF", "WOOD", "WOOL", "WORD", "WORE",
    "WORK", "WORM", "WRAP", "YARD", "YARN", "YEAR", "YELL", "ZERO", "ZONE", "ZOOM",
]

WORDS_5 = [
    "ABOUT", "ABOVE", "ABUSE", "ACTOR", "ACUTE", "ADEPT", "ADMIT", "ADOPT",
    "ADULT", "AFTER", "AGAIN", "AGENT", "AGREE", "AHEAD", "ALARM", "ALBUM",
    "ALERT", "ALIKE", "ALIVE", "ALLOW", "ALONE", "ALONG", "ALTER", "AMBER",
    "AMEND", "AMONG", "AMPLE", "ANGER", "ANGLE", "ANGRY", "ANKLE", "APART",
    "APPLE", "APPLY", "ARENA", "ARGUE", "ARISE", "ARMOR", "AROSE", "ARRAY",
    "ARROW", "ASIDE", "ASSET", "AUDIO", "AUDIT", "AVOID", "AWAKE", "AWARD",
    "AWARE", "BADLY", "BAKER", "BASES", "BASIC", "BASIS", "BEACH", "BEGAN",
    "BEGIN", "BEING", "BELOW", "BENCH", "BICEP", "BILLY", "BINGO", "BIRTH",
    "BLACK", "BLADE", "BLAME", "BLANK", "BLAST", "BLAZE", "BLIND", "BLOCK",
    "BLOOD", "BLOOM", "BLUNT", "BOARD", "BOAST", "BOOST", "BOOTH", "BOUND",
    "BOXER", "BRAIN", "BRAND", "BRASS", "BRAVE", "BREAD", "BREAK", "BREED",
    "BRIAR", "BRICK", "BRIDE", "BRIEF", "BRING", "BRISK", "BROAD", "BROKE",
    "BROWN", "BRUSH", "BUILD", "BUILT", "BUNCH", "BUNNY", "BURST", "BUYER",
    "CABIN", "CABLE", "CANDY", "CANOE", "CARRY", "CATCH", "CAUSE", "CHAIN",
    "CHAIR", "CHALK", "CHAOS", "CHARM", "CHART", "CHASE", "CHEAP", "CHECK",
    "CHESS", "CHEST", "CHIEF", "CHILD", "CHILL", "CHINA", "CHOSE", "CHUNK",
    "CIGAR", "CIVIL", "CLAIM", "CLAMP", "CLASP", "CLASS", "CLEAN", "CLEAR",
    "CLEAT", "CLERK", "CLICK", "CLIFF", "CLIMB", "CLOCK", "CLOSE", "CLOTH",
    "CLOUD", "COACH", "COAST", "COBRA", "COMET", "COUCH", "COULD", "COUNT",
    "COURT", "COVER", "CRACK", "CRAFT", "CRANE", "CRANK", "CRASH", "CRATE",
    "CRAZY", "CREAM", "CREEK", "CREPT", "CRIME", "CRISP", "CROAK", "CROSS",
    "CROWD", "CROWN", "CRUDE", "CRUMB", "CURVE", "CYCLE", "DAILY", "DAISY",
    "DANCE", "DATED", "DEALT", "DEATH", "DECOY", "DELAY", "DELTA", "DEPTH",
    "DINER", "DIRTY", "DITCH", "DODGE", "DOING", "DOUBT", "DOZEN", "DRAFT",
    "DRAMA", "DRANK", "DRAPE", "DRAWN", "DREAM", "DRESS", "DRIED", "DRILL",
    "DRINK", "DRIVE", "DROVE", "DWARF", "DWELL", "DYING", "EAGER", "EAGLE",
    "EARLY", "EARTH", "EIGHT", "EJECT", "ELDER", "ELITE", "ELOPE", "EMPTY",
    "ENEMY", "ENJOY", "ENTER", "ENTRY", "EQUAL", "ERROR", "ETHIC", "EVENT",
    "EVERY", "EXACT", "EXIST", "EXTRA", "FAIRY", "FAITH", "FALSE", "FANCY",
    "FAULT", "FAVOR", "FEAST", "FENCE", "FERRY", "FETCH", "FEVER", "FIBER",
    "FIELD", "FIFTH", "FIFTY", "FIGHT", "FILTH", "FINAL", "FIRST", "FIXED",
    "FJORD", "FLAIR", "FLAME", "FLASH", "FLASK", "FLEET", "FLESH", "FLICK",
    "FLING", "FLINT", "FLOAT", "FLOOD", "FLOOR", "FLORA", "FLOUR", "FLUID",
    "FOCUS", "FORCE", "FORGE", "FORTH", "FORTY", "FORUM", "FOUND", "FRAME",
    "FRANK", "FRAUD", "FRESH", "FRONT", "FROST", "FRUIT", "FUDGE", "FULLY",
    "FUNNY", "GAUGE", "GHOST", "GIANT", "GIRTH", "GIVEN", "GLASS", "GLAZE",
    "GLOBE", "GLOOM", "GLORY", "GLOVE", "GNOME", "GOING", "GOURD", "GRACE",
    "GRADE", "GRAIN", "GRAND", "GRANT", "GRAPE", "GRAPH", "GRASP", "GRASS",
    "GRAVE", "GRAVY", "GREAT", "GREED", "GREEN", "GREET", "GRIEF", "GRILL",
    "GRIME", "GRIMY", "GRIND", "GROAN", "GROIN", "GROOM", "GROSS", "GROUP",
    "GROWN", "GUARD", "GUESS", "GUEST", "GUIDE", "GUILT", "GULLY", "HABIT",
    "HAPPY", "HARDY", "HARSH", "HASTE", "HATCH", "HAZEL", "HEART", "HEAVY",
    "HEDGE", "HELLO", "HENCE", "HINGE", "HOARD", "HOBBY", "HONEY", "HONOR",
    "HORSE", "HOTEL", "HOUND", "HOUSE", "HOWDY", "HUMAN", "HUMOR", "HURRY",
    "HYENA", "ICING", "IDEAL", "IMAGE", "IMPLY", "INDEX", "INLET", "INNER",
    "INPUT", "IRATE", "IRONY", "ISSUE", "IVORY", "JEANS", "JELLY", "JOINT",
    "JOKER", "JUDGE", "JUICE", "JUMBO", "KAYAK", "KNACK", "KNEAD", "KNEEL",
    "KNIFE", "KNOCK", "KNOWN", "LABEL", "LABOR", "LAPSE", "LARGE", "LARVA",
    "LASER", "LATER", "LAUGH", "LAYER", "LEAKY", "LEAPT", "LEARN", "LEASE",
    "LEAST", "LEAVE", "LEDGE", "LEGAL", "LEMON", "LEVEL", "LEVER", "LIGHT",
    "LILAC", "LIMIT", "LINED", "LINEN", "LINER", "LINKS", "LIVER", "LOBBY",
    "LOCAL", "LOGIC", "LOOSE", "LOVER", "LOWER", "LOYAL", "LUCKY", "LUNCH",
    "LYING", "LYRIC", "MAGIC", "MAJOR", "MAKER", "MANGO", "MARCH", "MARRY",
    "MARSH", "MATCH", "MAYBE", "MAYOR", "MEANT", "MECCA", "MEDAL", "MEDIA",
    "MEDIC", "MELON", "MERCY", "MERIT", "MERRY", "MESSY", "METAL", "METER",
    "MIDST", "MIGHT", "MINOR", "MINUS", "MIRTH", "MIXED", "MODEL", "MOLAR",
    "MONEY", "MONTH", "MORAL", "MOSSY", "MOTOR", "MOUNT", "MOUSE", "MOUTH",
    "MOVIE", "MUCKY", "MUNCH", "MUSIC", "NADIR", "NAKED", "NASTY", "NAVAL",
    "NERDY", "NERVE", "NEVER", "NEWLY", "NICHE", "NIGHT", "NOBLE", "NOISE",
    "NOISY", "NORTH", "NOTED", "NOVEL", "NUDGE", "NURSE", "NYMPH", "OCCUR",
    "OCEAN", "OFFER", "OFTEN", "OLIVE", "ONION", "ONSET", "OPERA", "ORBIT",
    "ORDER", "ORGAN", "OTHER", "OUGHT", "OUTER", "OWNED", "OWNER", "OXIDE",
    "OZONE", "PAINT", "PANEL", "PANIC", "PAPER", "PARTY", "PASTA", "PATCH",
    "PAUSE", "PEACE", "PEARL", "PENNY", "PERCH", "PETTY", "PHASE", "PHONE",
    "PHOTO", "PIANO", "PIECE", "PILOT", "PITCH", "PIZZA", "PLACE", "PLAIN",
    "PLANE", "PLANK", "PLANT", "PLATE", "PLAZA", "PLEAD", "PLUCK", "PLUMB",
    "POACH", "POINT", "POLAR", "PORCH", "POUCH", "POUND", "POWER", "PREEN",
    "PRESS", "PRICE", "PRIDE", "PRIME", "PRIMP", "PRINT", "PRIOR", "PRIZE",
    "PROBE", "PROOF", "PROPS", "PROUD", "PROVE", "PUDGY", "PULSE", "PUPIL",
    "PUPPY", "PURSE", "QUACK", "QUAFF", "QUASH", "QUEEN", "QUERY", "QUEST",
    "QUEUE", "QUICK", "QUIET", "QUILL", "QUIRK", "QUITE", "QUOTA", "QUOTE",
    "RADIO", "RAISE", "RALLY", "RANCH", "RANGE", "RAPID", "RATIO", "REACH",
    "READY", "REALM", "REBAR", "REBEL", "REFER", "REIGN", "RELAX", "RELIC",
    "REPLY", "RHINO", "RIDER", "RIDGE", "RIFLE", "RIGHT", "RIGID", "RIVAL",
    "RIVER", "ROAST", "ROBIN", "ROBOT", "ROCKY", "ROUGE", "ROUGH", "ROUND",
    "ROUTE", "ROWDY", "ROYAL", "RUDDY", "RUGBY", "RULER", "RUMOR", "RURAL",
    "SADLY", "SAINT", "SALAD", "SALON", "SALTY", "SANDY", "SAUCE", "SAVOR",
    "SCALE", "SCARE", "SCARF", "SCENE", "SCOFF", "SCOLD", "SCOPE", "SCORE",
    "SCORN", "SCOUT", "SCRAP", "SCREW", "SEDAN", "SENSE", "SERVE", "SETUP",
    "SEVEN", "SHADE", "SHAFT", "SHAKE", "SHALL", "SHAME", "SHAPE", "SHARE",
    "SHARK", "SHARP", "SHEEN", "SHEEP", "SHEET", "SHELF", "SHELL", "SHIFT",
    "SHINE", "SHINY", "SHIRT", "SHOCK", "SHOOT", "SHORE", "SHORT", "SHOWN",
    "SHRUB", "SHRUG", "SIEGE", "SIGHT", "SILLY", "SINCE", "SIREN", "SIXTH",
    "SIXTY", "SKATE", "SKILL", "SKIRT", "SKULL", "SLANT", "SLATE", "SLEEP",
    "SLICE", "SLICK", "SLIDE", "SLIMY", "SLOPE", "SLUMP", "SMALL", "SMART",
    "SMELL", "SMILE", "SMIRK", "SMOKE", "SNAIL", "SNAKE", "SNEAK", "SNIFF",
    "SNORT", "SOLAR", "SOLID", "SOLVE", "SORRY", "SOUND", "SOUTH", "SPACE",
    "SPADE", "SPARE", "SPARK", "SPASM", "SPAWN", "SPEAK", "SPEED", "SPELL",
    "SPEND", "SPENT", "SPICE", "SPIKE", "SPINE", "SPITE", "SPLIT", "SPOKE",
    "SPOOL", "SPOON", "SPORT", "SPRAY", "SPRIG", "SPURT", "SQUAD", "SQUAT",
    "STACK", "STAFF", "STAGE", "STAIR", "STAKE", "STALK", "STAMP", "STAND",
    "STARE", "START", "STASH", "STATE", "STEAM", "STEEL", "STEEP", "STEER",
    "STEIN", "STERN", "STICK", "STIFF", "STILL", "STINK", "STOCK", "STOMP",
    "STONE", "STOOD", "STOOL", "STORE", "STORK", "STORM", "STORY", "STOUT",
    "STOVE", "STRAP", "STRAW", "STRIP", "STRUT", "STUDY", "STUFF", "STUNT",
    "STYLE", "SUAVE", "SUGAR", "SUITE", "SUNNY", "SUPER", "SURGE", "SUSHI",
    "SWAMP", "SWEAR", "SWEAT", "SWEEP", "SWEET", "SWEPT", "SWIFT", "SWING",
    "SWIRL", "SWOOP", "SWORD", "SYRUP", "TABBY", "TABLE", "TACKY", "TAKEN",
    "TANGO", "TARDY", "TASTE", "TASTY", "TAUNT", "TAXES", "TEACH", "TEASE",
    "TEETH", "TEMPO", "TENTH", "TEPID", "TERMS", "THANK", "THEFT", "THEIR",
    "THEME", "THERE", "THESE", "THICK", "THIEF", "THING", "THINK", "THIRD",
    "THORN", "THOSE", "THREE", "THREW", "THROW", "THUMB", "THUMP", "TIDAL",
    "TIGER", "TIGHT", "TIMER", "TITLE", "TOAST", "TODAY", "TOKEN", "TONIC",
    "TOOTH", "TOPIC", "TORCH", "TORSO", "TOTAL", "TOUCH", "TOUGH", "TOWER",
    "TOXIC", "TRACE", "TRACK", "TRADE", "TRAIL", "TRAIN", "TRAIT", "TRASH",
    "TRAWL", "TREAT", "TREND", "TRIAL", "TRIBE", "TRICK", "TRIED", "TRIES",
    "TRUCK", "TRULY", "TRUNK", "TRUST", "TRUTH", "TULIP", "TWEAK", "TWICE",
    "TWIRL", "TWIST", "UDDER", "ULCER", "ULTRA", "UMBRA", "UNCLE", "UNDER",
    "UNION", "UNITE", "UNITY", "UNTIL", "UPPER", "UPSET", "URBAN", "USAGE",
    "USHER", "USUAL", "VAGUE", "VALID", "VALUE", "VAPOR", "VAULT", "VENUE",
    "VERSE", "VIDEO", "VIGOR", "VINYL", "VIRAL", "VIRUS", "VISIT", "VITAL",
    "VIVID", "VIXEN", "VOCAL", "VODKA", "VOGUE", "VOICE", "VOTER", "VOUCH",
    "WAGER", "WAGON", "WAIST", "WALTZ", "WASTE", "WATCH", "WATER", "WAVER",
    "WEARY", "WEAVE", "WEDGE", "WEEDY", "WEIGH", "WEIRD", "WELSH", "WHALE",
    "WHARF", "WHEAT", "WHEEL", "WHERE", "WHICH", "WHILE", "WHITE", "WHOLE",
    "WHOSE", "WIDEN", "WIDOW", "WIDTH", "WINCE", "WINDY", "WISPY", "WITTY",
    "WOMAN", "WORLD", "WORRY", "WORSE", "WORST", "WORTH", "WOULD", "WOUND",
    "WOVEN", "WRATH", "WRECK", "WRING", "WRIST", "WRITE", "WRONG", "WROTE",
    "YACHT", "YEARN", "YIELD", "YOUNG", "YOURS", "YOUTH", "YUMMY", "ZEBRA",
    "ZESTY", "ZONAL",
]

WORDS_6 = [
    "ACCEPT", "ACCESS", "ACROSS", "ACTION", "ACTIVE", "ACTUAL", "ADVICE", "ADVISE",
    "AFFAIR", "AFFORD", "AFRAID", "AGENCY", "AGENDA", "ALMOST", "ALWAYS", "AMOUNT",
    "ANIMAL", "ANNUAL", "ANSWER", "ANYONE", "ANYWAY", "APPEAL", "APPEAR", "AROUND",
    "ARRIVE", "ARTIST", "ASPECT", "ASSIST", "ASSUME", "ATTACK", "ATTEND", "AUGUST",
    "AUTHOR", "AUTUMN", "AVENUE", "BAMBOO", "BANANA", "BANNER", "BARELY", "BARREL",
    "BATTLE", "BEAUTY", "BECOME", "BEFORE", "BEHALF", "BEHAVE", "BEHIND", "BELONG",
    "BESIDE", "BETTER", "BEYOND", "BISHOP", "BORDER", "BORROW", "BOTTLE", "BOTTOM",
    "BOUNCE", "BRANCH", "BREATH", "BRIDGE", "BRIGHT", "BROKEN", "BUDGET", "BUNDLE",
    "BURDEN", "BUREAU", "BUTTON", "CAMERA", "CAMPUS", "CANCEL", "CANCER", "CANDLE",
    "CANNON", "CANYON", "CARBON", "CAREER", "CARPET", "CARROT", "CASTLE", "CASUAL",
    "CAUGHT", "CELERY", "CEMENT", "CENTER", "CHANCE", "CHANGE", "CHARGE", "CHEESE",
    "CHERRY", "CHOICE", "CHOOSE", "CHROME", "CHURCH", "CIRCLE", "CLEVER", "CLIENT",
    "CLOSER", "CLOUDY", "COFFEE", "COLUMN", "COMBAT", "COMEDY", "COMMON", "COOKIE",
    "CORNER", "COTTON", "COUNTY", "COUPLE", "COURSE", "COUSIN", "CREATE", "CREDIT",
    "CRISIS", "CUSTOM", "DAMAGE", "DANGER", "DEALER", "DEBATE", "DECADE", "DECIDE",
    "DECENT", "DEFEAT", "DEFEND", "DEFINE", "DEGREE", "DEMAND", "DEPEND", "DEPLOY",
    "DESERT", "DESIGN", "DESIRE", "DETAIL", "DETECT", "DEVICE", "DINNER", "DIRECT",
    "DOCTOR", "DOLLAR", "DOMAIN", "DOUBLE", "DRAGON", "DRIVER", "DURING", "EASILY",
    "EDITOR", "EFFECT", "EFFORT", "EIGHTH", "EITHER", "EMERGE", "EMPIRE", "EMPLOY",
    "ENABLE", "ENERGY", "ENGAGE", "ENGINE", "ENOUGH", "ENROLL", "ENSURE", "ENTIRE",
    "ENTITY", "EQUITY", "ESCAPE", "ESTATE", "EXCEED", "EXCEPT", "EXCESS", "EXPAND",
    "EXPECT", "EXPERT", "EXPORT", "EXTEND", "EXTENT", "FABRIC", "FACING", "FACTOR",
    "FAIRLY", "FAMILY", "FAMOUS", "FATHER", "FELLOW", "FEMALE", "FIGURE", "FILTER",
    "FINGER", "FINISH", "FISCAL", "FLIGHT", "FLOWER", "FLYING", "FOLLOW", "FOREST",
    "FORGET", "FORMAL", "FORMAT", "FORMER", "FOSTER", "FOUGHT", "FOURTH", "FRIDGE",
    "FRIEND", "FROZEN", "FUTURE", "GADGET", "GALAXY", "GARAGE", "GARDEN", "GATHER",
    "GENDER", "GENTLE", "GERMAN", "GLOBAL", "GOLDEN", "GOSPEL", "GOSSIP", "GOVERN",
    "GRAVEL", "GROUND", "GROWTH", "GUITAR", "HAMMER", "HANDLE", "HAPPEN", "HARBOR",
    "HARDLY", "HAZARD", "HEALTH", "HEAVEN", "HEIGHT", "HELMET", "HEREBY", "HIDDEN",
    "HOLLOW", "HONEST", "HORROR", "HOSTEL", "HUMBLE", "HUNGRY", "HUNTER", "IGNORE",
    "IMPACT", "IMPORT", "IMPOSE", "INCOME", "INDEED", "INDOOR", "INFANT", "INFECT",
    "INFORM", "INJURY", "INSECT", "INSIDE", "INSIST", "INTACT", "INTEND", "INTENT",
    "INVENT", "INVEST", "INVITE", "ISLAND", "ITSELF", "JACKET", "JAGUAR", "JUNGLE",
    "JUNIOR", "KETTLE", "KIDNEY", "KITTEN", "LADDER", "LAPTOP", "LATTER", "LAUNCH",
    "LAWYER", "LAYOUT", "LEADER", "LEAGUE", "LEGACY", "LEGEND", "LENGTH", "LESSON",
    "LETTER", "LIKELY", "LINEAR", "LIQUID", "LISTEN", "LITTLE", "LIVELY", "LIVING",
    "LOCATE", "LOSING", "LOUNGE", "LOVELY", "LOWEST", "LUXURY", "MAINLY", "MAKEUP",
    "MANAGE", "MANNER", "MANUAL", "MARBLE", "MARGIN", "MARINE", "MARKET", "MASTER",
    "MATTER", "MATURE", "MEADOW", "MEDIUM", "MELODY", "MEMBER", "MEMORY", "MENTAL",
    "MENTOR", "MERELY", "METHOD", "MIDDLE", "MINUTE", "MIRROR", "MOBILE", "MODERN",
    "MODEST", "MODULE", "MOMENT", "MONKEY", "MOSTLY", "MOTION", "MOTIVE", "MUSEUM",
    "MUTUAL", "NARROW", "NATION", "NATIVE", "NATURE", "NEARBY", "NEARLY", "NEEDLE",
    "NEPHEW", "NICELY", "NOBODY", "NOTICE", "NOTION", "NUMBER", "OBJECT", "OBTAIN",
    "OCCUPY", "OFFICE", "OFFSET", "ONLINE", "OPTION", "ORANGE", "ORIGIN", "OUTPUT",
    "PALACE", "PARADE", "PARDON", "PARENT", "PARROT", "PASTRY", "PATROL", "PEANUT",
    "PENCIL", "PEOPLE", "PEPPER", "PERIOD", "PERMIT", "PERSON", "PHRASE", "PICKLE",
    "PICNIC", "PIGEON", "PILLOW", "PLANET", "PLAYER", "PLEASE", "PLENTY", "POCKET",
    "POETRY", "POLICE", "POLICY", "POLISH", "PORTAL", "POTATO", "POWDER", "PRAISE",
    "PRAYER", "PREFER", "PRETTY", "PRINCE", "PRISON", "PROFIT", "PROMPT", "PROPER",
    "PUBLIC", "PURPLE", "PURSUE", "PUZZLE", "QUARTZ", "RABBIT", "RACING", "RADISH",
    "RANDOM", "RARELY", "RATHER", "RATING", "REASON", "REBOOT", "RECALL", "RECENT",
    "RECIPE", "RECORD", "REDUCE", "REFORM", "REFUND", "REGARD", "REGION", "REGRET",
    "REJECT", "RELATE", "RELIEF", "REMAIN", "REMIND", "REMOTE", "REMOVE", "RENDER",
    "RENTAL", "REPAIR", "REPEAT", "REPLAY", "REPORT", "RESCUE", "RESORT", "RESULT",
    "RETAIL", "RETAIN", "RETIRE", "RETURN", "REVEAL", "REVIEW", "REWARD", "RHYTHM",
    "RIBBON", "RIDDLE", "ROCKET", "ROTATE", "RUBBER", "SADDLE", "SAFETY", "SALARY",
    "SALMON", "SAMPLE", "SAVAGE", "SAVING", "SCHEME", "SCHOOL", "SCREEN", "SEARCH",
    "SEASON", "SECOND", "SECRET", "SECTOR", "SECURE", "SELDOM", "SELECT", "SENIOR",
    "SENSOR", "SERVER", "SETTLE", "SEVERE", "SHADOW", "SHIELD", "SHRIMP", "SIGNAL",
    "SILENT", "SILVER", "SIMPLE", "SINGER", "SINGLE", "SISTER", "SKETCH", "SLEEVE",
    "SLIGHT", "SLOGAN", "SMOOTH", "SOCCER", "SOCIAL", "SOFTLY", "SOLELY", "SONNET",
    "SPEECH", "SPHERE", "SPIRIT", "SPLASH", "SPONGE", "SPRING", "SQUARE", "STABLE",
    "STAPLE", "STATUE", "STATUS", "STEADY", "STITCH", "STREAM", "STREET", "STRESS",
    "STRICT", "STRIKE", "STRING", "STRIPE", "STRONG", "STUDIO", "STUPID", "SUBMIT",
    "SUBTLE", "SUDDEN", "SUFFER", "SUMMER", "SUMMIT", "SUNSET", "SUPPLY", "SURELY",
    "SURVEY", "SWITCH", "SYMBOL", "SYNTAX", "SYSTEM", "TABLET", "TACKLE", "TAILOR",
    "TALENT", "TARGET", "TAUGHT", "TEMPLE", "TENANT", "TENDER", "TENNIS", "THEORY",
    "THIRTY", "THOUGH", "THREAD", "THREAT", "THRIVE", "THROAT", "THRONE", "THROWN",
    "TICKET", "TIMBER", "TIMING", "TISSUE", "TOGGLE", "TOMATO", "TONGUE", "TOWARD",
    "TRAGIC", "TRENDY", "TRIBAL", "TRIPOD", "TROPHY", "TUNNEL", "TURTLE", "TWELVE",
    "TWENTY", "TYPING", "UNABLE", "UNFAIR", "UNIQUE", "UNITED", "UNLOCK", "UNVEIL",
    "UPDATE", "UPLOAD", "URGENT", "USEFUL", "VALLEY", "VANISH", "VELVET", "VENDOR",
    "VERSUS", "VESSEL", "VICTIM", "VIEWER", "VIOLET", "VIRTUE", "VISION", "VISUAL",
    "VOLUME", "VOTING", "VOYAGE", "WALLET", "WALNUT", "WANDER", "WARMTH", "WEALTH",
    "WEAPON", "WEEKLY", "WIDELY", "WINNER", "WINTER", "WISDOM", "WITHIN", "WIZARD",
    "WONDER", "WOODEN", "WORKER", "WORTHY", "WRENCH", "WRITER", "YELLOW", "YONDER",
]

WORDS_BY_LENGTH = {
    4: WORDS_4,
    5: WORDS_5,
    6: WORDS_6,
}

SUPPORTED_LENGTHS = tuple(sorted(WORDS_BY_LENGTH))  # (4, 5, 6)
DEFAULT_LENGTH = 5

WORD_SETS = {n: set(words) for n, words in WORDS_BY_LENGTH.items()}


def get_random_word(length=DEFAULT_LENGTH):
    pool = WORDS_BY_LENGTH.get(length) or WORDS_BY_LENGTH[DEFAULT_LENGTH]
    return random.choice(pool)


def is_valid_word(word, length=None):
    """A guess is valid if it's in the curated list for its length."""
    word = (word or "").upper()
    if length is None:
        length = len(word)
    word_set = WORD_SETS.get(length)
    return bool(word_set) and word in word_set


def score_guess(guess, answer):
    """Standard Wordle scoring with correct duplicate-letter handling.

    Works for any word length; `guess` and `answer` are assumed equal length.
    """
    guess = guess.upper()
    answer = answer.upper()
    n = len(answer)
    result = ["absent"] * n
    remaining = {}
    for i in range(n):
        if guess[i] == answer[i]:
            result[i] = "correct"
        else:
            remaining[answer[i]] = remaining.get(answer[i], 0) + 1
    for i in range(n):
        if result[i] == "correct":
            continue
        ch = guess[i]
        if remaining.get(ch, 0) > 0:
            result[i] = "present"
            remaining[ch] -= 1
    return result
